USE pds;
SELECT COUNT(DISTINCT JOB_ID) FROM employees;

Select AVG(SALARY), COUNT(EMPLOYEE_ID) FROM employees WHERE DEPARTMENT_ID = 90;

SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM employees GROUP BY JOB_ID;

SELECT 
    FIRST_NAME, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM
    employees
        JOIN
    departments USING (DEPARTMENT_ID);

SELECT 
    FIRST_NAME, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME, CITY
FROM
    employees
        JOIN
    departments USING (DEPARTMENT_ID)
        JOIN
    locations USING (LOCATION_ID)
WHERE
    city = 'London';